default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hertz_development

test:
  <<: *default
  database: hertz_test

production:
  <<: *default
  database: hertz_production
